# Generated by Django 4.1.4 on 2024-03-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('highest_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
