# Generated by Django 4.1.4 on 2024-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
