# Generated by Django 4.1.4 on 2023-06-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_session_name_alter_school_name'),
        ('staff', '0002_department_created_at_department_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school'),
        ),
    ]
