# Generated by Django 4.1.4 on 2024-03-31 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffeducation_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffeducation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 1, 0, 40, 47, 313760)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffeducation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffpreviousexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 1, 0, 41, 0, 267123)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffpreviousexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
