# Generated by Django 4.1.4 on 2024-03-31 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerationnumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos/school/%Y/%m/%d/')),
                ('line1', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=300)),
                ('zip_code', models.CharField(blank=True, max_length=6)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolSessions', to='school.school')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='current_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentSession', to='school.session'),
        ),
    ]
