# Generated by Django 4.1.4 on 2023-05-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(blank=True, choices=[('user-admin', 'USER-ADMIN'), ('student', 'STUDENT'), ('staff', 'STAFF'), ('guradian', 'GURADIAN')], max_length=20, null=True, verbose_name='role'),
        ),
    ]
