# Generated by Django 4.1.4 on 2023-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profileLogo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/accounts/%Y/%m/%d/'),
        ),
    ]
