# Generated by Django 4.1.4 on 2023-05-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('accounts', '0003_alter_useraccount_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school'),
        ),
    ]
