# Generated by Django 4.1.4 on 2023-06-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_school_section_school_alter_class_name'),
        ('subjects', '0001_initial'),
        ('school', '0002_session_name_alter_school_name'),
        ('examsAndSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.session'),
        ),
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.session'),
        ),
        migrations.AddField(
            model_name='marks',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.session'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.courses'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.class'),
        ),
    ]
