# Generated by Django 4.1.4 on 2023-04-09 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjectID', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('bookName', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('syllabus', models.ImageField(blank=True, null=True, upload_to='subjects/%Y/')),
                ('classID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.class')),
            ],
        ),
    ]
